from api import app
from rag import (
    ASSISTANT_IDENTITY,
    CHAT_PROVIDER,
    DOMAIN_GUARDRAIL_ANSWER,
    FALLBACK_ANSWER,
    OPENROUTER_MODEL,
    OLLAMA_CHAT_MODEL,
    build_graph,
    build_page_content,
    corpus_question_match_score,
    document_key,
    format_context,
    generate_node,
    get_bm25_retriever,
    get_chat_model,
    get_embeddings,
    get_graph,
    get_latest_user_text,
    get_qa_corpus_documents,
    get_vector_store,
    invoke_graph,
    is_identity_query,
    lexical_overlap_score,
    message_to_text,
    metadata_match_score,
    normalize_dense_score,
    references_external_bank,
    rerank_documents,
    retrieve_node,
    safe_bm25_candidates,
    safe_dense_candidates,
    safe_lexical_candidates,
    safe_mmr_candidates,
    summarize_node,
    trim_node,
)
from settings import OLLAMA_BASE_URL, OPENROUTER_BASE_URL, THREAD_ID